### PR TITLE
Update README.md

### LINKED ISSUE #12: Social Links need Emphasis
## Description

The links to our community's activity sites are rather lost in the text - I'd suggest using Icons (like the one in my profile) or badges (shield.io or the like) to draw attention to these. If centred, it would also help reduce asymmetric whitespace

### PR DESCRIPTION
**Pull request by krishguptadev**
fixes #12

### CODE REVIEW

**Review by CodingSpecies — CHANGES_REQUESTED** [review]
@krishguptadev I think that perhaps if we were to go with the logos, they should be tranpsarent like this:



This is what I think, lets see what others say.

**Comment by CodingSpecies** [comment]
@krishguptadev is there any updates with this? Is there any help needed?
Thank you.

**Review by CodingSpecies — COMMENTED** [review]
@krishguptadev is there any updates? Do you need any help?
Thanks.

**Comment by krishguptadev** [comment]
Ah! There is some issue in the fork, I'll close this PR and make a new one with all the requested changes.

**Comment by krishguptadev** [comment]
#19

**Pull request closed without merging**
